# Generated by Django 5.1.1 on 2024-10-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=255, verbose_name='data_key')),
                ('data_value', models.CharField(max_length=255, verbose_name='data_value')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
            ],
        ),
    ]
