# Generated by Django 5.1.1 on 2025-01-10 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_nonodata_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonodata',
            options={'verbose_name': 'Nonoデータ', 'verbose_name_plural': 'Nonoデータ'},
        ),
        migrations.AlterField(
            model_name='nonodata',
            name='data_key',
            field=models.CharField(help_text='データのキーを入力してください', max_length=255, verbose_name='キー'),
        ),
        migrations.AlterField(
            model_name='nonodata',
            name='data_value',
            field=models.CharField(help_text='データの値を入力してください', max_length=255, verbose_name='値'),
        ),
        migrations.AlterField(
            model_name='nonodata',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='このデータに関連付ける日付', null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='nonodata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
